# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQfJwW9oh-O8r42_lTOpeHRSyDm97rvh
"""

import pandas as pd
import numpy as np

df = pd.read_csv("cmu1000_keywords_cleaned.csv")
df.head()

sample_text = """Physico-chemical characteristics of ground water from shallow wells in Galambi and its environ in Bauchi State, Northern Nigeria, were evaluated. A total of fifteen shallow well water samples were randomly collected and analyzed for an assessment of its potability and suitability for domestic purposes. Results obtained indicate that the ground water is slightly acidic to moderately alkaline (5.70< P H <8.10), hard to very hard, (124.7 – 256 mg/l), colourless, and odorless. Conductivity, HCO 3 2 -, CO 3 2 -, NO 3 2 -, SO 4 2 -, and PO 4 3 - are generally within WHO permissible levels for potable water. However, heavy metals like copper, iron, and lead are of higher concentrations than WHO standards for drinking water. Consequently, relevant treatment procedures are strongly recommended to reduce concentrations of Fe, Cu and Pb in the water so as to minimize the risks/concerns that they may pose to human health within and around the study area. The plot of the average constituents of the ground water in a Piper Trilinear diagram shows that the water is potable and can be classified as alkaline earth water type with higher alkaline proportion (Ca – Mg – Na) and predominantly HCO 3 - water, as well as normal alkaline earth water type (Ca – Mg) with predominantly HCO 3 - water."""

goals = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]

def calc(text):
    match_score = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    text_len = len(text.split())
    for i in range(len(df)):
        count = text.count(df.keyword[i])
        match_score[df.goal[i] - 1] += (df.weight[i] * count)/text_len
    return match_score

res = calc(sample_text)
for i in range(17):
    print(goals[i], res[i])