# -*- coding: utf-8 -*-
"""pdf_handler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dp6ORqvLUCVI3jqCFzhMhk6B_2_olkjA
"""
from pymongo import MongoClient
import PyPDF2
import requests as rq
import os
from pathlib import Path
from string import digits

if not os.path.exists("/tmp/"):
    os.makedirs("/tmp/")
    os.chmod("/tmp/", 0o777)

def get_pdf_content(url):
    
    try:
        res = rq.get(url, stream=True)
        #pdfFileObj = open(res.content, 'rb')

        filename = Path('/tmp/temp.pdf')
        filename.write_bytes(res.content)

        # creating a pdf file object
        pdfFileObj = open('/tmp/temp.pdf', 'rb')
        
        # creating a pdf reader object
        pdfReader = PyPDF2.PdfReader(pdfFileObj)
            
        pdf_content = ""

        for page in pdfReader.pages:
                
            s = page.extract_text()
            remove_digits = str.maketrans('', '', digits)
            text = s.translate(remove_digits)
                
            pdf_content += " " + text
        
        return pdf_content
    except:
        print("Bad Response url:{}".format(url))
        return ""
